---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: quay.io/centos/centos:7
    privileged: True
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: rockylinux
    image: robertdebock/rockylinux
    command: /sbin/init
    privileged: True
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  options:
    D: True
 
verifier:
  name: testinfra
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
#    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
