---
- name: StepSSH | Check is installed
  ansible.builtin.stat:
    path: /usr/bin/step
  register: is_stepssh_installed

- name: StepSSH | Download install script
  ansible.builtin.get_url:
    url: https://files.smallstep.com/ssh-host.sh
    dest: /tmp/ssh-host.sh
    mode: '0750'
  when: not is_stepssh_installed.stat.exists

- name: StepSSH | Build array of tags
  set_fact:
    classyllama_stepssh_tag_string: "--tag {{ classyllama_stepssh_tags | list | join(' --tag ') }}"

- name: StepSSH | Debug
  ansible.builtin.debug:
    var: classyllama_stepssh_tag_string

- name: StepSSH | Installation
  ansible.builtin.command: >
         bash /tmp/ssh-host.sh 
         --team {{ classyllama_stepssh_teamid }}
         --token {{ classyllama_stepssh_token }}
         --hostname {{ classyllama_stepssh_fqdn }}
         {{ classyllama_stepssh_bastion_config }}
         {{ classyllama_stepssh_tag_string }}
         --force

  ignore_errors: '{{ ansible_check_mode }}'
  register: command_output
  when: not is_stepssh_installed.stat.exists

- name: StepSSH | Debug
  ansible.builtin.debug:
    var: command_output.stdout_lines

- name: StepSSH | Reconfigure step-ssh-meta to sync user-data into temp file
  ansible.builtin.template:
    src: step-ssh-metadata.service.j2
    dest: "/etc/systemd/system/step-ssh-metadata.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd configuration
    - restart step-ssh-metadata
  when: classyllama_stepssh_replace_bash

- name: StepSSH | Upload script for step-ssh-meta
  ansible.builtin.template:
    src: step-ssh-meta-replace.sh.j2
    dest: "/usr/local/bin/step-ssh-meta-replace.sh"
    owner: root
    group: root
    mode: 0750
  when: classyllama_stepssh_replace_bash

- name: StepSSH | Adding cron entry
  ansible.builtin.cron:
    name: "step-ssh-meta-replace"
    minute: "*"
    job: "/usr/local/bin/step-ssh-meta-replace.sh"
    user: root
  when: classyllama_stepssh_replace_bash
