---
# Define the supported ansible version requirements of these playbooks
ansible_version_require_min: "2.11.3"         # Example "2.10" or "2"
ansible_version_require_min_operator: ">="  # Example ">=" or ">"
ansible_version_require_max: "3"            # Example "2.11" or "3"
ansible_version_require_max_operator: "<"   # Example "<=" or "<"

# ---- System Configs ----
app_domain: example.lan

yum_update_and_reboot: never # (always, initial, never)

use_classyllama_syseng_access: true
use_classyllama_boilerplate: true
use_geerlingguy_repo_epel: true
use_classyllama_repo_ius: true

use_classyllama_timezone: false
timezone_name: America/Chicago

syseng_access_users: []

use_kamaln7_swapfile: false
swapfile_location: /var/swap.1
swapfile_size: 2048
swapfile_swappiness: 10
swapfile_use_dd: true

use_classyllama_python: true
use_classyllama_repo_python_appstream: false
python_package_name: python # CentOS 7 uses Python 2.7
python_software_packages: 
  - "{{ python_package_name }}"
  - "{{ python_package_name }}-pip"
  - "{{ python_package_name }}-devel"

use_linuxhq_postfix: true
postfix_parameters:
    smtp_tls_security_level: encrypt
    smtp_use_tls: True
    smtp_tls_note_starttls_offer: True
    smtp_tls_CAfile: /etc/ssl/certs/ca-bundle.crt
    inet_protocols: ipv4
    mydomain: "{{ ansible_domain }}"
    myhostname: "{{ ansible_nodename }}"
    mynetworks_style: host
    mynetworks:
      - 127.0.0.0/8
postfix_packages:
- cyrus-sasl
- cyrus-sasl-lib
- cyrus-sasl-plain

# --- PHP ----
use_geerlingguy_php: true
php_enable_webserver: false
php_enable_repo: "ius"
php_packages:
  - php74-cli
  - php74-common
  - php74-devel
  - php74-fpm
  - php74-gd
  - php74-ldap
  - php74-mbstring
  - php74-opcache
  - php74-pdo
  - php74-xml
  - php74-xmlrpc
  - php74-json

php_enable_apc: false
php_memory_limit: "512M"

# ---- Bastion tools ----
use_classyllama_lshell: true
use_classyllama_stepssh: true
classyllama_stepssh_token: "token"
use_classyllama_mcb: true
use_classyllama_pk_delivery: true
