---

- ansible.builtin.import_playbook: playbooks/check_ansible_version.yml
- ansible.builtin.import_playbook: playbooks/common.yml

- ansible.builtin.import_playbook: playbooks/bastion.yml
  when: inventory_hostname in groups['bastion']
